# Generated by Django 4.1.13 on 2025-12-20 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jounrey_Date', models.DateField()),
                ('Number_of_seats', models.IntegerField()),
                ('Seat_number', models.CharField(max_length=20)),
                ('Booking_status', models.CharField(choices=[('Pending', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='Pending', max_length=20)),
                ('Booking_date', models.DateTimeField(auto_now_add=True)),
                ('pnr', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Train_number', models.IntegerField(unique=True)),
                ('Train_name', models.CharField(max_length=50)),
                ('Source', models.CharField(max_length=50)),
                ('Destination', models.CharField(max_length=50)),
                ('Departure_Time', models.DateTimeField()),
                ('Arrival_Time', models.DateTimeField()),
                ('Total_seats', models.IntegerField()),
                ('Available_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Payment_Status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='train.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='Train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.train'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
