# Generated by Django 4.1.13 on 2025-12-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Jounrey_Date',
            new_name='Journey_Date',
        ),
    ]
