# Generated by Django 4.1.13 on 2025-12-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_rename_jounrey_date_booking_journey_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Payment_Status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=50),
        ),
    ]
