# Generated by Django 4.1.13 on 2025-12-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0005_booking_seats_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seats_booked',
        ),
    ]
